version: '2.1'

services:
  syscoin-libjs:
    image: syscoin-libjs
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8881:8881
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 dist/index.js